# Generated by Django 5.1.7 on 2025-04-01 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.IntegerField(choices=[(1, 'Inactive'), (2, 'Guest'), (3, 'User'), (4, 'Verified'), (5, 'Moderator'), (6, 'Admin')], default=3),
        ),
    ]
