# Generated by Django 5.1.7 on 2025-04-03 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_customuser_verification_code_emailverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='theme',
            field=models.IntegerField(choices=[(1, 'rose-quartz'), (2, 'arctic-blue'), (3, 'cool-lavender'), (4, 'pastel-mint'), (5, 'linen-light'), (6, 'classic-dark'), (7, 'midnight-blue'), (8, 'charcoal'), (9, 'graphite'), (10, 'dusk-mode'), (11, 'classic')], default=11),
        ),
    ]
